### ISSUE TITLE
Not working on Apple M1

### ISSUE THREAD

**Issue by sungkhum** [yukinarit/apnggif#5]
I was getting errors installing on a Mac M1

`error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration] if (LSEEK(state->fd, state->start, SEEK_SET) == -1)`

To fix, use homebrew to install the latest GCC
`brew install gcc`

Then set to use homebrew's gcc:
```
cd /opt/homebrew/bin      
ln -s gcc-11 gcc
ln -s g++-11 g++
```
Close your terminal

And using `where gcc` - find the path and put it in the command below:
`env CC=/opt/homebrew/bin/gcc pip3 install apnggif`

It should install successfully then.

**Comment by yukinarit** [comment]
Hi @sungkhum  
Which python version are you using?

**Comment by sungkhum** [comment]
@yukinarit Python 3.9.9
I was able to install but still ran into this bug after and was unable to resolve: https://github.com/yukinarit/apnggif/issues/4

**Comment by yukinarit** [comment]
@sungkhum 
Pushed v0.1.4 to PyPI. Could you verify it?

**Comment by yukinarit** [comment]
Should have been fixed.
